# Generated by Django 4.2.2 on 2024-05-08 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "ordering": ("-payment_date",),
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
            },
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 8, 21, 49, 13, 754128, tzinfo=datetime.timezone.utc
                ),
                verbose_name="дата платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_sum",
            field=models.FloatField(verbose_name="сумма платежа"),
        ),
    ]
