# Generated by Django 5.0.4 on 2024-05-10 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_options_alter_payments_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 10, 14, 35, 54, 227904, tzinfo=datetime.timezone.utc
                ),
                verbose_name="дата платежа",
            ),
        ),
    ]
