# Generated by Django 5.0.4 on 2024-05-23 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_payment_date_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Cсылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 23, 19, 35, 0, 746014, tzinfo=datetime.timezone.utc
                ),
                verbose_name="дата платежа",
            ),
        ),
    ]
